src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\ORM\Mapping as ORM;

 #[ORM\Entity(repositoryClass: EventsRepository::class)] 
class Events
{ 
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]   
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'datetime')]
    private $date_time;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\Column(type: 'integer')]
    private $capacity;

    #[ORM\Column(type: 'string', length: 50)]
    private $email;

    #[ORM\Column(type: 'integer')]
    private $phone;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'string', length: 255)]
    private $url;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): self
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;

use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;




class EventsType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options): void
  {
      $builder
          ->add('name', TextType::class, [
              'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('capacity', TextType::class, [
              'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('description', TextType::class, [
              'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('email', TextType::class, [
            'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('url', TextType::class, [
            'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('address', TextType::class, [
            'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('phone', TextType::class, [
            'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
          ])
          ->add('date_time', DateTimeType::class, [
              'attr' => ['style' => 'margin-bottom:15px']
          ])
          ->add('image', FileType::class, [
            'label' => 'Upload Picture',
//unmapped means that is not associated to any entity property
            'mapped' => false,
//not mandatory to have a file
            'required' => false,

//in the associated entity, so you can use the PHP constraint classes as validators
            'constraints' => [
                new File([
                    'maxSize' => '5048k', // 14
                    'mimeTypes' => [
                        'image/png',
                        'image/jpeg',
                        'image/jpg',
                    ],
                    'mimeTypesMessage' => 'Please upload a valid image file',
                ])
            ],
        ])

          ->add('save', SubmitType::class, [
              'label' => 'Create event',
              'attr' => ['class' => 'btn-primary', 'style' => 'margin-bottom:15px']
          ]);
  }

  public function configureOptions(OptionsResolver $resolver): void
  {
      $resolver->setDefaults([
          'data_class' => Events::class,
      ]);
  }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;

use Doctrine\Persistence\ManagerRegistry;
use App\Form\EventsType;
use Symfony\Component\HttpFoundation\Request;
use App\Service\FileUploader;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Events;

class EventsController extends AbstractController
{
    #[Route('/', name: 'events')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $events = $doctrine->getRepository(Events::class)->findAll();

        return $this->render('events/index.html.twig', ['events' => $events]);
        
    }

    #[Route('/create', name: 'events_create')]
   public function create(Request $request, ManagerRegistry $doctrine, FileUploader $fileUploader): Response
   {
       $events = new Events();
       $form = $this->createForm(EventsType::class, $events);

       $form->handleRequest($request);

/* Here we have an if statement, if we click submit and if  the form is valid we will take the values from the form and we will save them in the new variables */
       if($form->isSubmitted() && $form->isValid()){

            $name = $form['name']->getData();
            $description = $form['description']->getData();
            $image = $form['image']->getData();
            $capacity = $form['capacity']->getData();
            $email = $form['email']->getData();
            $phone = $form['phone']->getData();
            $address = $form['address']->getData();
            $url = $form['url']->getData();
            $date_time = $form['date_time']->getData();

            $events->setName($name);
            $events->setDescription($description);
            $events->setImage($image);
            $events->setCapacity($capacity);
            $events->setEmail($email);
            $events->setPhone($phone);
            $events->setAddress($address);
            $events->setUrl($url);
            $events->setDateTime($date_time);

    //         $em = $doctrine->getManager();
    //         $em->persist($events);
    //         $em->flush();

    //        $this->addFlash(
    //            'notice',
    //            'Event Added'
    //            );
     
    //        return $this->redirectToRoute('events');
    //    }
    //    return $this->render('events/create.html.twig', ['form' => $form->createView()]);
           $now = new \DateTime('now');
           $imageFile = $form->get('image')->getData();
           //imageUrl is the name given to the input field
           if ($imageFile) {
             $imageFileName = $fileUploader->upload($imageFile);
             $events->setImage($imageFileName);
           }
 
           $events = $form->getData();
           $events->setDateTime($now);  
           $em = $doctrine->getManager();
           $em->persist($events);
           // $status = $doctrine->getRepository(Status::class)->find(1);
           $em->flush();

           $this->addFlash(
               'notice',
               'Event Added'
               );
     
           return $this->redirectToRoute('events');
       }
       return $this->render('events/create.html.twig', ['form' => $form->createView()]);
    }


    #[Route('/edit/{id}', name: 'events_edit')]
    public function edit(Request $request, ManagerRegistry $doctrine, $id): Response
    {
        $events = $doctrine->getRepository(Events::class)->find($id);
        $form = $this->createForm(EventsType::class, $events);
        $form->handleRequest($request);
  
        if ($form->isSubmitted() && $form->isValid()) {

            $events->setName($events->getName());
            $events->setDescription($events->getDescription());
            $events->setImage($events->getImage());
            $events->setCapacity($events->getCapacity());
            $events->setEmail($events->getEmail());
            $events->setPhone($events->getPhone());
            $events->setAddress($events->getAddress());
            $events->setUrl($events->getUrl());
            $events->setDateTime($events->getDateTime());

            $em = $doctrine->getManager();
            $em->persist($events);
            $em->flush();

            $this->addFlash(
                'notice',
                'Event has been succesfuly changed'
            );
  
            return $this->redirectToRoute('events');
        }
  
        return $this->render('events/edit.html.twig', ['form' => $form->createView()]);
    }

  #[Route('/details/{id}', name: 'events_details')]
  public function details(ManagerRegistry $doctrine, $id): Response
  {
      $events = $doctrine->getRepository(Events::class)->find($id);
    // dd($events);
      return $this->render('events/details.html.twig', ['events' => $events]);
  }

  #[Route('/delete/{id}', name: 'events_delete')]
  public function delete(ManagerRegistry $doctrine, $id): Response
  {
    $em = $doctrine->getManager();
    $events = $em->getRepository('App:Events')->find($id);
    $em->remove($events);
    
    $em->flush();
    $this->addFlash(
        'notice',
        'Event Removed'
    );  
    return $this->redirectToRoute('events');
}

}

templates/events/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create New Event{% endblock %}

{% block body %}

<h1 class="text-center">Create new Event</h1>
<div class="container mt-3 mb-3">
<div class="row d-flex justify-content-center">
<div class="col-12 com-sm-10 col-md-8 col-lg-6">
<div class="form-body  p-5">
    {{form_start(form)}}
    {{form_widget(form)}}
    {{form_end(form)}}
    <a href="/"><button class="btn btn-dark mx-2" title="back"> Go back</button></a>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/events/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EventsController!{% endblock %}

{% block body %}
<div class="container">
    <h2 class="page-header">Delete Event {{events.name}}</h2>
    <img src="{{events.image}}" class="img-thumbnail" alt="{{events.name}}">

</div>
{% endblock %}

templates/events/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details{% endblock %}

{% block body %}

<div class="container">
        <div class="col-sm-10 offset-sm-1 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <div class="card mb-4 border-0 my-5" >
                <div class="card-body bg-light rounded-3 bg-light">
                    <img src=" ../pictures/{{ events.image }} " class="card-img-top">
                    <h5 class="card-title text-center"> {{ events.name }} </h5>                   
                    <p class="d-flex justify-content-center"></p>
                    <div class="card-text ms-4 ">
                        <p class="m-0 ">Description: {{ events.description }}</p>
                        <p class="m-0 ">Capacity: {{ events.capacity }}</p>
                        <p class="m-0 ">Email: {{ events.email }}</p>
                        <p class="m-0 ">Phone: {{ events.phone }}</p>
                        <p class="m-0 ">Address: {{ events.address }}</p>
                        <p class="m-0 ">URL: {{ events.url }}</p>
                        <p class="m-0">Date: {{events.dateTime | date('d/m/Y')}}</p>
                        <p class="m-0">Time: {{events.dateTime | date('H:i')}}</p>
                    </div>
                    <div class="d-flex justify-content-center my-3">
                        <a href="/edit/{{ events.id }}"><button class="btn btn-dark mx-2" title="edit">Edit the Event</button></a>
                        <a href="/delete/{{ events.id }}" onclick="return confirm('Confirm to delete')" class="btn btn-dark mx-2">Delete the Event</a>
                        <a href="/"><button class="btn btn-dark mx-2" title="back"> Go back</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit the Event{% endblock %}

{% block body %}
    <h2 class="page-header text-center">Edit Event:</h2>
    <div class="container mt-3 mb-3">
    <div class="row d-flex justify-content-center">
    <div class="col-12 com-sm-10 col-md-8 col-lg-6">
    <div class="form-body  p-5">
    {{form_start(form)}}
    {{form_widget(form)}}
    {{form_end(form)}}
        </div>
    <a href="/"><button class="btn btn-dark mx-5" title="back"> Go back</button></a>

</div>
</div>
</div>
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome to Big Events{% endblock %}

{% block body %}

<section id="events">
    <div class="container mt-3 mb-3">
        <h2 class="text-center m-5"> Welcome to our site, <br> we do hope that you can find <br> something that is going to be interesting to you.</h2>
        <hr>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-5">
            {% for event in events %}
            <div class="col">
                <div class="card h-100 mb-5 ">
                <img src="../pictures/{{event.image}}" class="card-img-top style" alt="{{ event.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.name }}</h5>
                        <p class="card-text">{{event.description}}</p>
                        <div class="m-3">
                            <p class="card-text m-0">Date: {{event.dateTime | date('d/m/Y ')}}</p>
                            <p class="card-text m-0">Time: {{event.dateTime | date('H:i')}} </p>
                        </div>                       
                        <div>
                            <a href="/details/{{event.id}}" class="btn btn-dark">Details</a>
                            <a href="/edit/{{event.id}}" class="btn btn-dark">Edit</a>
                            <a href="/delete/{{event.id}}" onclick="return confirm('Confirm to delete')" class="btn btn-dark">Delete</a>
                        </div>
                    </div>
                </div>
                </div>
            {% endfor %}
    </div>
</section>
{% endblock %}